import {
  Award,
  BadgeCheck,
  Battery,
  Car,
  CircleDot,
  Cog,
  Compass,
  Cpu,
  Disc,
  Droplets,
  Eye,
  Gauge,
  Hammer,
  Paintbrush,
  RotateCcw,
  ScanSearch,
  Shield,
  Sparkles,
  Wrench,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import type { ServiceIconName } from '@/lib/service-data';

export const SERVICE_ICONS: Record<ServiceIconName, LucideIcon> = {
  award: Award,
  'badge-check': BadgeCheck,
  battery: Battery,
  car: Car,
  'circle-dot': CircleDot,
  cog: Cog,
  compass: Compass,
  cpu: Cpu,
  disc: Disc,
  droplets: Droplets,
  eye: Eye,
  gauge: Gauge,
  hammer: Hammer,
  paintbrush: Paintbrush,
  'rotate-ccw': RotateCcw,
  scan: ScanSearch,
  shield: Shield,
  sparkles: Sparkles,
  wrench: Wrench,
};
